name: 'autorelease'
description: 'autorelease new versions'
inputs:
  github_token:
    description: 'API Token for Github'
    required: true
  openai_token:
    description: 'API Token for OpenAI'
    required: false
    default: ''
outputs:
runs:
  using: "composite"
  steps:
    - run: exit 0
