name: Autorelease

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-bash/actions/instrument/workflow@v4.12.3
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'
  
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./Scheduler/
    steps:
      - uses: plengauer/autorelease@v0.1.0
