name: Release
on:
  push:
    branches: main
    paths:
      - 'VERSION'
      
jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
        id: version
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: AutoRelease v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
